# Generated by Django 5.2.6 on 2025-09-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_gender_alter_myuser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
